#!/bin/bash

HOSTNAME=$(hostname)

cd .config/kitty

if [ "$HOSTNAME" == "laptop" ]; then
    ln -s "kitty.laptop.conf" "kitty.conf"
elif [ "$HOSTNAME" == "desktop" ]; then
    ln -s "kitty.desktop.conf" "kitty.conf"
else
    echo "Unknown hostname: $HOSTNAME. Exiting."
    exit 1
fi
